---
title: "Highcharter"
subtitle: "<br>shorturl.at/jCX09<br>"
author: "Duc-Quang Nguyen"
date: "2022/05/19"
output: 
  revealjs::revealjs_presentation:
    theme: serif
    echo: TRUE
    warning: FALSE
    message: FALSE
---



```{r load packages,warning=FALSE,message=FALSE}
library(tidyverse)
library(sf)
library(highcharter)
library(htmltools)
#install.packages(c("htmltools", leaflet", "highcharter"))
```

# Highchart(er)

Highcharts is very flexible and customizable javascript charting library and it has a great and powerful API.
 
+  Good performance, heaps of chart options, syntax quite similar to ggplot2
-  Free for personal/non-commercial uses and paid for commercial applications
 
* [Highcharter](https://jkunst.com/highcharter/)
* [Highcharts](https://www.highcharts.com)


---

## Sankey chart

<small>
[Le dilemme européen du gaz russe décrypté en 6 graphiques](https://www.letemps.ch/economie/dilemme-europeen-gaz-russe-decrypte-6-graphiques)
</small>

```{r load data}
df <- read_csv("data/EuropeanGasPipeline.csv") %>% 
  # highcharts needs these column names
   rename(
    from = De,
    to = Vers,
    weight = value
  ) 

df <- df %>%  
  mutate(from = str_c(from, " ")) %>% 
  # need a unique id for each ribbon
  mutate(id = str_c(from, to) %>% str_remove_all("(-|'| )")) %>% 
  select(from, to, weight, id) %>% 
  mutate(weight = round(weight, 1))

hc_sankey_chart <- df %>% 
  mutate(from = fct_reorder(from, weight, sum,.desc = T)) %>% 
  arrange(desc(from)) %>% 
  hchart(
    "sankey", 
    name = "Gaz naturel par gazoduc",
         nodePadding = 5, linkOpacity = 0.6) %>% 
  hc_tooltip(
      valueDecimals = 2
    ) %>% 
  hc_size(height = 600) 

```


## Standalone htmlwidget

```{r export to html}

descr <- str_c(
  "Flux du gaz naturel par gazoduc en Europe, en 2020 et en milliards de mètres cubes<br>",
  "<span style='color: #999; display: inline-block; margin-top: .25em;font-size:0.8em'>◉ <i>Placer votre curseur/tapoter sur un ruban pour afficher davantage d'informations</i></span>"
) 

save_html(
  tags$html(
    tags$head(
     # includeCSS()
      #includeHTML("letemps_style.html")
    ),
    tags$body(
      h1("Plus d'un tiers du gaz naturel acheminé en Europe par gazoduc provient de Russie"),
      div(class = "descr", HTML(descr)),
      hc_sankey_chart,
    )),
  file = "fluxGasNaturelEuropeSankey.html", libdir = "js"
)

```





https://datawrapper.dwcdn.net/F3wwJ/5/

